services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_STREAM=webhooks
    depends_on:
      - redis
  delivery:
    build:
      context: .
      dockerfile: Dockerfile.delivery
    environment: &environment
      - REDIS_HOST=redis
      - REDIS_STREAM=webhooks
      - REDIS_CONSUMER_GROUP=webhooks-consumer-group
    depends_on:
      - redis
      - api
      - echoserver-0
      - echoserver-1
  delivery-pending:
    build:
      context: .
      dockerfile: Dockerfile.delivery
    command: ["python3", "delivery_pending.py"]
    environment: *environment
    depends_on:
      - redis
  redis:
    image: redis:alpine
  echoserver-0: &echoserver
    image: nginx
  echoserver-1: *echoserver
  redis-init:
    image: redis:alpine
    # add backend server mappings to echoservers
    command:
      - sh
      - -c
      - |
        redis-cli -h redis set "backend:0" "echoserver-0"
        redis-cli -h redis set "backend:1" "echoserver-1"
    depends_on:
      - redis
  redis-stream-stats:
    image: redis:alpine
    environment:
      - REDIS_HOST=redis
      - REDIS_STREAM=webhooks
      - REDIS_CONSUMER_GROUP=webhooks-consumer-group
    command:
      - sh
      - -c
      - |
        while true; do
          sleep 5
          export REDIS_XLEN=$$(redis-cli -h $${REDIS_HOST} --raw XLEN $${REDIS_STREAM})
          export REDIS_XPENDING=$$(redis-cli -h $${REDIS_HOST} --raw XPENDING $${REDIS_STREAM} $${REDIS_CONSUMER_GROUP} | head -n 1)
          echo "webhooks: $${REDIS_XLEN}"
          echo "webhooks-pending: $${REDIS_XPENDING}"
        done
    depends_on:
      - redis
      - redis-init
