services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment: &environment
      - REDIS_HOST=redis
      - REDIS_STREAM=webhooks
      - REDIS_DLQ_STREAM=webhooks-dlq
      - REDIS_CONSUMER_GROUP=webhooks-consumer-group
      - REDIS_DLQ_CONSUMER_GROUP=webhooks-dlq-consumer-group
    depends_on:
      - redis
  delivery:
    build:
      context: .
      dockerfile: Dockerfile.delivery
    environment: *environment
    depends_on:
      - redis
      - api
  delivery-dlq:
    build:
      context: .
      dockerfile: Dockerfile.delivery
    environment:
      - REDIS_HOST=redis
      - REDIS_STREAM=webhooks
      - REDIS_DLQ_STREAM=webhooks-dlq
      - REDIS_CONSUMER_GROUP=webhooks-consumer-group
      - REDIS_DLQ_CONSUMER_GROUP=webhooks-dlq-consumer-group
      - DELIVERY_DLQ=true
    depends_on:
      - redis
      - api
  redis:
    image: redis:alpine
  echoserver-1: &echoserver
    image: nginx
    depends_on:
      - delivery
  echoserver-2: *echoserver
  redis-init:
    image: redis:alpine
    # add backend server mappings to echoservers
    command:
      - sh
      - -c
      - |
        redis-cli -h redis set "backend:1" "echoserver-1"
        redis-cli -h redis set "backend:2" "echoserver-2"
    depends_on:
      - redis
