FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip

WORKDIR /app

COPY requirements.delivery.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY src/modules modules
COPY src/delivery.py delivery.py
COPY src/delivery_pending.py delivery_pending.py

CMD ["python3", "delivery.py"]
