apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitiw.fullname" . }}-api
  labels:
    {{- include "gitiw.labels" . | nindent 4 }}
    role: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitiw.selectorLabels" . | nindent 6 }}
      role: api
  template:
    metadata:
      labels:
        {{- include "gitiw.labels" . | nindent 8 }}
        role: api
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- with .Values.api.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /up
              port: http
          readinessProbe:
            httpGet:
              path: /up
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
