apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    {{- include "gitiw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.echoserver.service.type }}
  ports:
    - port: {{ .Values.echoserver.service.port }}
      targetPort: {{ .Values.echoserver.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "gitiw.selectorLabels" . | nindent 4 }}
    role: echoserver
