apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitiw.fullname" . }}
  labels:
    {{- include "gitiw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gitiw.selectorLabels" . | nindent 4 }}
    role: api
